<?php
global $events_types;
if(function_exists("register_field_group")) {
	register_field_group(array (
		'id' => 'acf_tribe_events',
		'title' => 'Event',
		'fields' => array (
			array ( // audience
				'key' => 'field_56bb75cb2b770',
				'label' => 'Audience',
				'name' => 'audience',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array ( // objectives
				'key' => 'field_56bb755469083',
				'label' => 'Objectives',
				'name' => 'objectives',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array ( // prerequisites
				'key' => 'field_56bb7361c90e2',
				'label' => 'Prerequisites',
				'name' => 'prerequisites',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array ( // functionality
				'key' => 'field_56f9249fd9a10',
				'label' => 'Functionality',
				'name' => 'functionality',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array ( // industry
				'key' => 'field_56f924f2d9a12',
				'label' => 'Theme',
				'name' => 'theme',
				'type' => 'taxonomy',
				'instructions' => 'Select event theme.',
				'taxonomy' => 'theme',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array ( // type
				'key' => 'field_56bc6747e3379',
				'label' => 'Event Type',
				'name' => 'event_type',
				'type' => 'select',
				'instructions' => '',
				'required' => '0',
				'choices' => $events_types,
				'default_value' => '',
				'allow_null' => '0',
				'multiple' => '0',
				'conditional_logic' => array (
					'status' => '0',
					'rules' => array (
						0 => array (
							'field' => 'null',
							'operator' => '==',
						),
					),
					'allorany' => 'all',
				),
				'order_no' => 0,
			),
			array ( // technology
				'key' => 'field_56f924b5d9a11',
				'label' => 'Technology',
				'name' => 'technology',
				'type' => 'taxonomy',
				'instructions' => 'Select event technology. You can select more than one by holding Ctrl button',
				'taxonomy' => 'technology',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array ( // platform
				'key' => 'field_56f92505d9a13',
				'label' => 'Platform',
				'name' => 'platform',
				'type' => 'taxonomy',
				'instructions' => 'Select event platform. You can select more than one by holding Ctrl button',
				'taxonomy' => 'platform',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array ( // interest
				'key' => 'field_56f92513d9a14',
				'label' => 'Interest',
				'name' => 'interest',
				'type' => 'taxonomy',
				'instructions' => 'Select event interest. You can select more than one by holding Ctrl button',
				'taxonomy' => 'interest',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'tribe_events',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_venue',
		'title' => 'Venue',
		'fields' => array (
			array (
				'key' => 'field_56dbfbe8515df',
				'label' => 'gmap',
				'name' => 'gmap',
				'type' => 'google_map',
				'required' => 1,
				'center_lat' => '30.046',
				'center_lng' => '31.225',
				'zoom' => 6,
				'height' => 400,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'tribe_venue',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
?>
