<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_be_product',
		'title' => 'be_product',
		'fields' => array (
			array (
				'key' => 'field_569ce8cdc94db',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Write product description',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_569ce8f0c94dc',
				'label' => 'Developer',
				'name' => 'developer',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Enter product developer',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_569ce909c94dd',
				'label' => 'Functionality',
				'name' => 'functionality',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_569ce91cc94de',
				'label' => 'Category',
				'name' => 'industry',
				'type' => 'taxonomy',
				'instructions' => 'Select product category.',
				'taxonomy' => 'industry',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_569ce94cc94df',
				'label' => 'Usage hints',
				'name' => 'usage_hints',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Enter product usage hints',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_569ce964c94e0',
				'label' => 'References',
				'name' => 'references',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Enter product references',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_569cea3e4f5f9',
				'label' => 'Link to source',
				'name' => 'link_to_source',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://example.com',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_569cea814f5fa',
				'label' => 'Type',
				'name' => 'type',
				'type' => 'taxonomy',
				'instructions' => 'Select product type.
  You can select more than one by holding Ctrl button',
				'taxonomy' => 'type',
        'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_569ceabd4f5fb',
				'label' => 'Technology',
				'name' => 'technology',
				'type' => 'taxonomy',
				'instructions' => 'Select product technology.
	You can select more than one by holding Ctrl button',
				'taxonomy' => 'technology',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_569ceb4b4f5fc',
				'label' => 'Platform',
				'name' => 'platform',
				'type' => 'taxonomy',
				'instructions' => 'Select product platform.
	You can select more than one by holding Ctrl button',
				'taxonomy' => 'platform',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_569ceb6c4f5fd',
				'label' => 'License',
				'name' => 'license',
				'type' => 'taxonomy',
				'instructions' => 'Select product license.
	You can select more than one by holding Ctrl button',
				'taxonomy' => 'license',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_569cebb54f5fe',
				'label' => 'Interest',
				'name' => 'interest',
				'type' => 'taxonomy',
				'instructions' => 'Select product interest.
	You can select more than one by holding Ctrl button',
				'taxonomy' => 'interest',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}


/*
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_add_product_from_backend',
		'title' => 'add_product_from_backend',
		'fields' => array (
			array (
				'key' => 'field_569ab65acdfca',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Write product description',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_569ab6c8cdfcb',
				'label' => 'Developer',
				'name' => 'developer',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Enter product developer',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_569ab726cdfcc',
				'label' => 'Functionality',
				'name' => 'functionality',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Enter product functionality',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_569ab745cdfcd',
				'label' => 'Industry',
				'name' => 'industry',
				'type' => 'taxonomy',
				'taxonomy' => 'industry',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_569ab7b7cdfce',
				'label' => 'Usage hints',
				'name' => 'usage_hints',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Enter product usage hints',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_569ab7dbcdfcf',
                                    'label' => 'References',
				'name' => 'references',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Enter product references',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_569ab7ffcdfd0',
				'label' => 'Link to source',
				'name' => 'link_to_source',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://example.com',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_569ab81ecdfd1',
				'label' => 'Type',
				'name' => 'type',
				'type' => 'taxonomy',
				'taxonomy' => 'type',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_569ab83fcdfd2',
				'label' => 'Technology',
				'name' => 'technology',
				'type' => 'taxonomy',
				'taxonomy' => 'technology',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_569ab865cdfd3',
				'label' => 'Platform',
				'name' => 'platform',
				'type' => 'taxonomy',
				'taxonomy' => 'platform',
				'field_type' => 'multi_select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_569ab886cdfd4',
				'label' => 'License',
				'name' => 'license',
				'type' => 'taxonomy',
				'taxonomy' => 'license',
				'field_type' => 'multi_select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_569ab8adcdfd5',
				'label' => 'Keywords',
				'name' => 'keywords',
				'type' => 'taxonomy',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'null',
							'operator' => '==',
							'value' => '',
						),
					),
					'allorany' => 'all',
				),
				'taxonomy' => 'keywords',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
*/
/*
add_magic_meta_box('first_test_metabox',
array(
'title' => 'First Test Metabox',
'pages' => array('page', 'post', 'product'),
'context' => 'normal',
'priority' => 'high',
'tabs' => array('basic' => 'Basic', 'advanced' => 'Advanced'),
'fields' => array(
array(
'type' => 'gallery',
'name' => 'Text Input',
'desc' => 'Put Your Name Here ',
'id' => 'text_one',
'placeholder' => 'Enter Your Name',
'tab' => 'basic',
),
)
));
*/
?>