<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_request-center-fields',
		'title' => 'request center fields',
		'fields' => array (
			array (
				'key' => 'field_5728669be92dc',
				'label' => 'type',
				'name' => 'request_center_type',
				'type' => 'taxonomy',
				'taxonomy' => 'request_center_type',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_572866e7e92dd',
				'label' => 'target bussiness relationship',
				'name' => 'target_bussiness_relationship',
				'type' => 'taxonomy',
				'taxonomy' => 'target_bussiness_relationship',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_57286726e92de',
				'label' => 'theme',
				'name' => 'theme',
				'type' => 'taxonomy',
				'taxonomy' => 'theme',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_57286759e92df',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_572867b0e92e0',
				'label' => 'requirements',
				'name' => 'requirements',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_572867d7e92e1',
				'label' => 'constraints',
				'name' => 'constraints',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_572867e4e92e2',
				'label' => 'technologies',
				'name' => 'technology',
				'type' => 'taxonomy',
				'taxonomy' => 'technology',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_57286816e92e3',
				'label' => 'related interests',
				'name' => 'interest',
				'type' => 'taxonomy',
				'taxonomy' => 'interest',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_57286972e92e4',
				'label' => 'deadline',
				'name' => 'deadline',
				'type' => 'date_picker',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'yy-mm-dd',
				'first_day' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'request_center',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

