# Generated by DBDiff
# On 01/13/2016 03:34:43 pm

INSERT INTO `en_revision` VALUES('3','3','3','Created page with \"FOSSPedia is the main source for education for Egypt FOSS platform.  == Featured Topics == * [[Egypt_FOSS | Egypt FOSS]]   == Latest Topics == * [[Egypt_FOSS | Egypt FOSS]]\"','1','Foss','20160113132533','0','0','172','0','a6s8hq49vngvcumgb0iqy4i775fum36','','');
INSERT INTO `en_revision` VALUES('2','2','2','Created page with \"FOSSPedia\"','1','Foss','20160113131926','0','0','9','0','2c9gq6ilmfnxze4p638kzplsrq7dfoy','','');
INSERT INTO `en_recentchanges` VALUES('4','20160113132557','1','Foss','0','Egypt_FOSS','Created page with \"Egypt FOSS is a platform for free and open source software community\"','0','0','1','4','4','0','1','mw.new','1','127.0.0.1','0','68','0','0','','','');
INSERT INTO `en_revision` VALUES('4','4','4','Created page with \"Egypt FOSS is a platform for free and open source software community\"','1','Foss','20160113132557','0','0','68','0','7akjqwcpcncescwxybqc3bu6gctiors','','');
INSERT INTO `en_text` VALUES('2','FOSSPedia','utf-8');
INSERT INTO `en_text` VALUES('4','Egypt FOSS is a platform for free and open source software community','utf-8');
INSERT INTO `en_text` VALUES('3','[[ar:مركز_المعرفة | مركز المعرفة]]

FOSSPedia is the main source for education for Egypt FOSS platform.

== Featured Topics ==
* [[Egypt_FOSS | Egypt FOSS]]


== Latest Topics ==
* [[Egypt_FOSS | Egypt FOSS]]','utf-8');
INSERT INTO `en_recentchanges` VALUES('3','20160113132533','1','Foss','0','FOSSPedia','Created page with \"FOSSPedia is the main source for education for Egypt FOSS platform.  == Featured Topics == * [[Egypt_FOSS | Egypt FOSS]]   == Latest Topics == * [[Egypt_FOSS | Egypt FOSS]]\"','0','0','1','3','3','0','1','mw.new','1','127.0.0.1','0','172','0','0','','','');
INSERT INTO `en_recentchanges` VALUES('2','20160113131926','1','Foss','8','Mainpage','Created page with \"FOSSPedia\"','0','0','1','2','2','0','1','mw.new','1','127.0.0.1','0','9','0','0','','','');
INSERT INTO `en_page` VALUES('2','8','Mainpage','','0','1','0.08177000391','20160113131926','20160113131926','2','9','wikitext','');
INSERT INTO `en_page` VALUES('4','0','Egypt_FOSS','','0','1','0.893667278116','20160113132557','20160113132557','4','68','wikitext','');
INSERT INTO `en_page` VALUES('3','0','FOSSPedia','','0','1','0.435852230013','20160113132557','20160113132533','3','172','wikitext','');
INSERT INTO `en_logging` VALUES('2','patrol','patrol','20160113132533','1','Foss','0','FOSSPedia','3','','a:3:{s:8:\"4::curid\";i:3;s:9:\"5::previd\";i:0;s:7:\"6::auto\";i:1;}','0');
INSERT INTO `en_logging` VALUES('1','patrol','patrol','20160113131926','1','Foss','8','Mainpage','2','','a:3:{s:8:\"4::curid\";i:2;s:9:\"5::previd\";i:0;s:7:\"6::auto\";i:1;}','0');
INSERT INTO `en_logging` VALUES('3','patrol','patrol','20160113132557','1','Foss','0','Egypt_FOSS','4','','a:3:{s:8:\"4::curid\";i:4;s:9:\"5::previd\";i:0;s:7:\"6::auto\";i:1;}','0');

INSERT INTO `ar_interwiki` (iw_prefix, iw_url, iw_local, iw_trans) VALUES ('en', 'http://egyptfoss.com/en/wiki/$1', 1, 0);
INSERT INTO `en_interwiki` (iw_prefix, iw_url, iw_local, iw_trans) VALUES ('ar', 'http://egyptfoss.com/ar/wiki/$1', 1, 0);


INSERT INTO `ar_logging` VALUES('2','patrol','patrol','20160113135610','1','Foss','0','مركز_المعرفة','3','','a:3:{s:8:\"4::curid\";i:3;s:9:\"5::previd\";i:0;s:7:\"6::auto\";i:1;}','0');
INSERT INTO `ar_logging` VALUES('1','patrol','patrol','20160113135358','1','Foss','8','Mainpage','2','','a:3:{s:8:\"4::curid\";i:2;s:9:\"5::previd\";i:0;s:7:\"6::auto\";i:1;}','0');
INSERT INTO `ar_page` VALUES('2','8','Mainpage','','0','1','0.707931749319','20160113135358','20160113135358','2','23','wikitext','');
INSERT INTO `ar_text` VALUES('3',' [[en:FOSSPedia | FOSSPedia]]
مركز المعرفه هو 

== مواضيع مختارة ==
* 
== اخر المواضيع ==
*','utf-8');
INSERT INTO `ar_recentchanges` VALUES('2','20160113135358','1','Foss','8','Mainpage','أنشأ الصفحة ب\'مركز المعرفة\'','0','0','1','2','2','0','1','mw.new','1','127.0.0.1','0','23','0','0','','','');
INSERT INTO `ar_page` VALUES('3','0','مركز_المعرفة','','0','1','0.732402618425','20160113135610','20160113135610','3','97','wikitext','');
INSERT INTO `ar_recentchanges` VALUES('3','20160113135610','1','Foss','0','مركز_المعرفة','أنشأ الصفحة ب\'مركز المعرفه هو   == مواضيع مختارة == *  == اخر المواضيع == *\'','0','0','1','3','3','0','1','mw.new','1','127.0.0.1','0','97','0','0','','','');
INSERT INTO `ar_revision` VALUES('2','2','2','أنشأ الصفحة ب\'مركز المعرفة\'','1','Foss','20160113135358','0','0','23','0','eaf3awb3k2sgeezri7zfxyso9j44f1u','','');
INSERT INTO `ar_text` VALUES('2','مركز المعرفة','utf-8');
INSERT INTO `ar_revision` VALUES('3','3','3','أنشأ الصفحة ب\'مركز المعرفه هو   == مواضيع مختارة == *  == اخر المواضيع == *\'','1','Foss','20160113135610','0','0','97','0','moaak75wwyl95r0v8uxwkar3nx1r51l','','');
