<?php
# This file was automatically generated by the MediaWiki 1.25.3
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
require_once('../db-config.php');
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "مركز المعرفة"." – EgyptFOSS";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/wiki";
$wgScriptExtension = ".php";

$actions = array( 'edit', 'watch', 'unwatch', 'delete','revert', 'rollback',
  'protect', 'unprotect', 'markpatrolled', 'render', 'submit', 'history', 'purge', 'info' );
 
foreach ( $actions as $action ) {
  $wgActionPaths[$action] = "/ar$wgScriptPath/$1/$action";
}
$wgActionPaths['view'] = "/ar/wiki/$1";
$wgArticlePath      = $wgActionPaths['view'];
$wgUsePathInfo      = true;

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://egyptfoss.com";

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";
$wgResourceBasePath = $wgScriptPath;

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@wiki.egyptfoss.com";
$wgPasswordSender = "apache@wiki.egyptfoss.com";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = constant('EF_DB_DRIVER');
$wgDBserver = constant('PEDIA_DB_HOST');
$wgDBname = constant('PEDIA_DB_NAME');
$wgDBuser = constant('PEDIA_DB_USER');
$wgDBpassword = constant('PEDIA_DB_PASSWORD');

# MySQL specific settings
$wgDBprefix = constant('PEDIA_DB_PREFIX_AR');

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgGroupPermissions['autoconfirmed']['upload'] = true;
$wgGroupPermissions['autoconfirmed']['reupload'] = true;
$wgGroupPermissions['user']['upload'] = true;
$wgFileExtensions = array('png', 'gif', 'jpg', 'jpeg', 'bmp');
//'doc', 'xls', 'mpp', 'pdf', 'ppt', 'tiff', 'docx', 'xlsx', 'pptx', 'ps', 'psd', 'swf', 'fla', 'mp3', 'mp4', 'm4v', 'mov', 'avi'
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "ar";

$wgSecretKey = "408bbf5226469c3694729dea7a4799f51f55e6fb1fb593461f516c63a1c8640c";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "d4f0dd455cb89a51";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
require_once( "skins/MediaWikiBootstrap/MediaWikiBootstrap.php" );
$wgDefaultSkin = "mediawikibootstrap";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'CologneBlue' );
wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );


# End of automatically generated settings.
# Add more configuration options below.


# Extension:WPMW https://www.mediawiki.org/wiki/Extension:WPMW
$wgGroupPermissions['*']['createaccount'] = false;

$wgAuthWPRelPath = '../';

require_once "extensions/AuthWP/AuthWP.php";
$wgAuth=new AuthWP();

$wpuser = wp_get_current_user();

# Permits of Anonymous
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['read'] = true;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['createpage'] = false;
$wgGroupPermissions['*']['createtalk'] = false;
# Permits of Users
if ( wp_user_can($wpuser, 'perform_direct_ef_actions') ) {
        //check if permission administrator
        if(wp_user_role($wpuser, 'administrator'))
        {
            $wgGroupPermissions['user']['delete'] = true;
            $wgGroupPermissions['user']['protect'] = true;
        }
	$wgGroupPermissions['user']['edit'] = true;
	$wgGroupPermissions['user']['createpage'] = true;
	$wgGroupPermissions['user']['minoredit'] = true;
} else {
	$wgGroupPermissions['user']['edit'] = false;
	$wgGroupPermissions['user']['createpage'] = false;
	$wgGroupPermissions['user']['minoredit'] = false;
}
$wgGroupPermissions['user']['move'] = false;
$wgGroupPermissions['user']['createtalk'] = false;
$wgGroupPermissions['user']['upload'] = false;
$wgGroupPermissions['user']['reupload'] = false;
$wgGroupPermissions['user']['reupload-shared'] = false;
# Permits of Administrators
$wgGroupPermissions['sysop']['move'] = true;
$wgGroupPermissions['sysop']['edit'] = true;
$wgGroupPermissions['sysop']['createpage'] = true;
$wgGroupPermissions['sysop']['createtalk'] = true;
$wgGroupPermissions['sysop']['upload'] = true;
$wgGroupPermissions['sysop']['reupload'] = true;
$wgGroupPermissions['sysop']['reupload-shared'] = true;
$wgGroupPermissions['sysop']['minoredit'] = true;

# these settings to enable url rewriting in mediwiki
# also the following lines need to be added to the virtual host
/*
location / {
    try_files $uri $uri/ @rewrite;
}

location @rewrite {
    rewrite ^/(.*)$ /index.php;
}

 */

$wgInterwikiMagic = true;
$wgExtraInterlanguageLinkPrefixes = array("en");

wfLoadExtension( 'WikiEditor' );