# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

VAGRANTFILE_API_VERSION ="2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "trusty64"
  	config.vm.box_url = "trusty-server-cloudimg-amd64-vagrant-disk1.box"
	config.vm.provider "virtualbox" do |vb|
    		vb.memory = 4048
		vb.cpus = 2
		end
	config.vm.network "forwarded_port", guest: 80, host: 8000
	config.vm.network "private_network", ip: "192.168.100.105"
	config.vm.provision "shell", path: "./wp_setup.sh"
end
