# Generated by DBDiff
# On 12/21/2015 04:46:03 pm

UPDATE `wpRuvF8_options` SET `option_value` = 'egyptfoss' WHERE `option_name` = 'template';
UPDATE `wpRuvF8_options` SET `option_value` = 'egyptfoss' WHERE `option_name` = 'stylesheet';
