# Generated by DBDiff
# On 12/20/2015 05:33:07 pm

INSERT INTO `wpRuvF8_posts` VALUES (NULL,'1','2015-12-15 16:29:36','2015-12-15 14:29:36','','Activate','','publish','closed','closed','','activate','','','2015-12-15 16:29:36','2015-12-15 14:29:36','','0','http://egyptfoss.com/activate/','0','page','','0');

INSERT INTO `wpRuvF8_options` VALUES (NULL,'smtp_port','587','yes');
INSERT INTO `wpRuvF8_options` VALUES (NULL,'smtp_host','smtp.mandrillapp.com','yes');
INSERT INTO `wpRuvF8_options` VALUES (NULL,'mail_set_return_path','','yes');
INSERT INTO `wpRuvF8_options` VALUES (NULL,'smtp_ssl','none','yes');
INSERT INTO `wpRuvF8_options` VALUES (NULL,'smtp_auth','true','yes');
INSERT INTO `wpRuvF8_options` VALUES (NULL,'smtp_pass','','yes');
INSERT INTO `wpRuvF8_options` VALUES (NULL,'smtp_user','testapp@espace.ws','yes');
INSERT INTO `wpRuvF8_options` VALUES (NULL,'mailer','smtp','yes');
INSERT INTO `wpRuvF8_options` VALUES (NULL,'mail_from_name','EgyptFOSS','yes');
INSERT INTO `wpRuvF8_options` VALUES (NULL,'mail_from','testapp@espace.ws','yes');

UPDATE `wpRuvF8_options` SET `option_value` = 'a:3:{i:0;s:24:\"buddypress/bp-loader.php\";i:1;s:29:\"wp-mail-smtp/wp_mail_smtp.php\";i:2;s:42:\"wordpress-social-login/wp-social-login.php\";}' WHERE `option_name` = 'active_plugins';
