# Generated by DBDiff
# On 01/18/2016 12:46:20 pm

INSERT INTO `wpRuvF8_bp_xprofile_groups` VALUES('1','Base','','0',0);
INSERT INTO `wpRuvF8_bp_xprofile_data` VALUES('1','1','1','foss','2016-01-18 10:45:34');
INSERT INTO `wpRuvF8_bp_xprofile_fields` VALUES('1','1','0','textbox','Name','',1,0,'0','0','',0);
