# Generated by DBDiff
# On 01/18/2016 04:09:28 pm
UPDATE `wpRuvF8_options` SET `option_value` = 'a:6:{i:0;s:21:\"polylang/polylang.php\";i:1;s:30:\"advanced-custom-fields/acf.php\";i:2;s:24:\"buddypress/bp-loader.php\";i:3;s:41:\"featured-galleries/featured-galleries.php\";i:4;s:42:\"wordpress-social-login/wp-social-login.php\";i:5;s:29:\"wp-mail-smtp/wp_mail_smtp.php\";}' WHERE `option_name` = 'active_plugins';

