# Generated by DBDiff
# On 01/18/2016 11:50:52 am

UPDATE `wpRuvF8_options` SET `option_value` = 'a:5:{s:8:\"xprofile\";s:1:\"1\";s:8:\"settings\";s:1:\"1\";s:8:\"activity\";s:1:\"1\";s:13:\"notifications\";s:1:\"1\";s:7:\"members\";s:1:\"1\";}' WHERE `option_name` = 'bp-active-components';
