# Generated by DBDiff
# On 02/26/2016 09:00:40 pm

SET @lastInsertedPost = (SELECT max(ID) from wpRuvF8_posts);
SET @newPostId = (select @lastInsertedPost) + 1;
INSERT INTO `wpRuvF8_posts` VALUES((select @newPostId),'1','2016-02-26 09:00:40','2016-02-26 09:00:40','','FOSS Map','','publish','closed','closed','','foss-map','','','2016-02-26 09:00:40','2016-02-26 09:00:40','','0',concat('http://egyptfoss.com/?page_id=',(select @newPostId),'/'),'0','page','','0');
INSERT INTO `wpRuvF8_postmeta` VALUES (NULL,(select @newPostId),'_wp_page_template','page-add-user-location.php');

SET @newPostId = (SELECT ID FROM wpRuvF8_posts where post_name = 'foss-map' limit 1);

SET @lastInsertedPost = (SELECT max(ID) from wpRuvF8_posts);
SET @arabicPostId = (select @lastInsertedPost) + 1;

INSERT INTO `wpRuvF8_posts` VALUES((select @arabicPostId),'1','2016-02-26 09:00:40','2016-02-26 09:00:40','','FOSS Map','','publish','closed','closed','','ar-foss-map','','','2016-02-26 09:00:40','2016-02-26 09:00:40','','0',concat('http://egyptfoss.com/?page_id=',(select @arabicPostId)),'0','page','','0');
INSERT INTO `wpRuvF8_postmeta` VALUES (NULL,(select @arabicPostId),'_wp_page_template','page-add-user-location.php');

INSERT INTO `wpRuvF8_terms` VALUES (NULL,'pll_56d0a36a56f81','pll_56d0a36a56f81','0','pll_56d0a36a56f81');
SET @lastInsertedID = (select last_insert_id());
INSERT INTO `wpRuvF8_term_taxonomy` VALUES (NULL,(select @lastInsertedID),'post_translations',concat('a:2:{s:2:\"ar\";i:',(select @arabicPostId),';s:2:\"en\";i:',(select @newPostId),';}'),'0','2');
SET @lastInsertedID = (select last_insert_id());
INSERT INTO `wpRuvF8_term_relationships` VALUES((select @arabicPostId),(select @lastInsertedID),'0');
INSERT INTO `wpRuvF8_term_relationships` VALUES((select @newPostId),(select @lastInsertedID),'0');


SET @term_ar_6 = (SELECT term_id FROM `wpRuvF8_terms` WHERE `slug` = 'ar' limit 1);
SET @term_tax_id_6 = (SELECT term_taxonomy_id from  `wpRuvF8_term_taxonomy` WHERE `term_id` =  (select @term_ar_6));
INSERT INTO `wpRuvF8_term_relationships` VALUES((select @arabicPostId),(select @term_tax_id_6),'0');

SET @term_en_3 = (SELECT term_id FROM `wpRuvF8_terms` WHERE `slug` = 'en' limit 1);
SET @term_tax_id_3 = (SELECT term_taxonomy_id from  `wpRuvF8_term_taxonomy` WHERE `term_id` =  (select @term_en_3));
INSERT INTO `wpRuvF8_term_relationships` VALUES((select @newPostId),(select @term_tax_id_3),'0');