# Generated by DBDiff
# On 04/11/2016 01:54:35 pm

UPDATE `wpRuvF8_posts` SET `post_status` = 'private', `post_modified` = '2016-04-11 10:54:14', `post_modified_gmt` = '2016-04-11 10:54:14' WHERE `post_title` = 'Members';
UPDATE `wpRuvF8_posts` SET `post_status` = 'private', `post_modified` = '2016-04-11 10:54:14', `post_modified_gmt` = '2016-04-11 10:54:14' WHERE `post_title` = 'الاعضاء';