# Generated by DBDiff
# On 07/21/2016 03:06:43 pm

UPDATE `wpRuvF8_posts` SET post_title = 'اقترح منتجاً' WHERE post_name = 'ar-add-product' AND post_type = 'page';
UPDATE `wpRuvF8_posts` SET post_title = 'اقترح فعالية' WHERE post_name = 'ar-add-event' AND post_type = 'page';
UPDATE `wpRuvF8_posts` SET post_title = 'اقترح خبراً' WHERE post_name = 'ar-add-news' AND post_type = 'page';

UPDATE `wpRuvF8_posts` SET post_title = 'اقترح قصة نجاح' WHERE post_name = 'ar-add-success-story' AND post_type = 'page';
UPDATE `wpRuvF8_posts` SET post_title = 'اقترح بيانات مفتوحة' WHERE post_name = 'ar-suggest-open-dataset' AND post_type = 'page';

UPDATE `wpRuvF8_posts` SET post_title = 'رد الطلب' WHERE post_name = 'ar-request-thread' AND post_type = 'page';