# Generated by DBDiff
# On 08/01/2016 06:00:16 pm

UPDATE `wpRuvF8_options` SET `option_value` = '587' WHERE `option_name` = 'smtp_port';
UPDATE `wpRuvF8_options` SET `option_value` = 'smtp.sparkpostmail.com' WHERE `option_name` = 'smtp_host';
UPDATE `wpRuvF8_options` SET `option_value` = 'none' WHERE `option_name` = 'smtp_ssl';
UPDATE `wpRuvF8_options` SET `option_value` = 'true' WHERE `option_name` = 'smtp_auth';
UPDATE `wpRuvF8_options` SET `option_value` = '52bdbce8b2ab8f5764270b9aca785ae2ae11faf4' WHERE `option_name` = 'smtp_pass';
UPDATE `wpRuvF8_options` SET `option_value` = 'SMTP_Injection' WHERE `option_name` = 'smtp_user';
	