# Generated by DBDiff
# On 10/26/2016 05:29:32 pm

ALTER TABLE wpRuvF8_api_keys CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE wpRuvF8_ef_reviews CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE wpRuvF8_efb_actions CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE wpRuvF8_efb_badges CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE wpRuvF8_efb_badges_actions CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE wpRuvF8_efb_badges_history CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE wpRuvF8_efb_badges_users CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE wpRuvF8_efb_credited_user_posts CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE wpRuvF8_mlw_qm_audit_trail CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE wpRuvF8_mlw_questions CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE wpRuvF8_mlw_quizzes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE wpRuvF8_mlw_results CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;