# Generated by DBDiff
# On 11/07/2016 12:38:54 pm

INSERT INTO `wpRuvF8_efb_actions` (`id`, `name`, `post_type`, `post_status`, `description`, `is_point_granted`, `parent_id`, `points_weight`) VALUES (NULL, 'publish_thought', 'expert_thought', 'publish', NULL, '1', NULL, '10');